HOST: baseURL/username/deviceName/currentQueue

--- Project Music Box v1 ---

---
Documentation of WAMP protocol between MusicBox & clients
---

--
Track Handling

Used to modify the queue
--

Message sent to add array of tracks to all listeners
GET /addTrack
< 200
< Content-Type: application/json
{  "command":"addTrack"
   "data": [
        {
            "url": "http://www.example.com/123", 
            "trackName":"Get Lucky", 
            "artistName": "Daft Punk", 
            "albumName": "Random Access Memories",
            "service": "Spotify", 
        }
    ] 
}

--
Control Commands

Isssued to control music box playback
--

GET /playTrack
< 200
< Content-Type: application/json
{  
    "command":"playTrack"
}

GET /pauseTrack
< 200
< Content-Type: application/json
{  
    "command":"pauseTrack"
}

GET /nextTrack
< 200
< Content-Type: application/json
{  
    "command":"nextTrack"
}

GET /endOfTrack
< 200
< Content-Type: application/json
{  
    "command":"endOfTrack"
}

--
RPC Calls

Used to poll server for static information
--


Make call to baseURL/players with args username,password to recieve array of avaliable player names
GET /players
< 200
[
    "playerName1",
    "playerName2"
]

Make call to baseURL/currentQueueRequest with args username,password,playerTitle to recieve statusUpdate message. This call returns nothing but a statusUpdate message from the box will follow on usual topic
GET /currentQueueRequest
< 200
{
    nil
}

--
Queue Managment 

Maintain and inform about current queue of tracks to all interested parties (MusicBox & Clients). 
Notice capital letters to track properties (due to shortcut in go; might change latter)
--


GET statusUpdate
< 200
{   "command":"statusUpdate"
    "data":{ 
        "deviceName": "My Device Name"
        "isPlaying": 1
        "queue":[
            {
                "Url": "http://www.example.com/123", 
                "TrackName":"Get Lucky", 
                "ArtistName": "Daft Punk",
                "AlbumName": "Random Access Memories",
                "Service": "Spotify", 
            }
        ]
    }
}