HOST: baseURL/username/deviceName/currentQueue

--- Project Music Box v1 ---

---
Documentation of WAMP protocol between MusicBox & clients
---

--
Track Handling

Used to modify the queue
--

Message sent to add array of tracks to all listeners
PUT /addTrack
> Content-Type: application/json
{  
    "command":"addTrack"
    "data": [
        {
            "url": "http://www.example.com/123", 
            "trackName":"Get Lucky", 
            "artistName": "Daft Punk", 
            "albumName": "Random Access Memories",
            "service": "Spotify", 
        }
    ] 
}
< 200

--
Control Commands

Isssued to control music box playback
--

PUT /playTrack
> Content-Type: application/json
{  
    "command":"playTrack"
}
< 200


PUT /pauseTrack
> Content-Type: application/json
{  
    "command":"pauseTrack"
}
< 200


PUT /nextTrack
> Content-Type: application/json
{  
    "command":"nextTrack"
}
< 200


GET /endOfTrack
< 200
< Content-Type: application/json
{  
    "command":"endOfTrack"
}


--
RPC Calls

Used to poll server for static information
--


Make call to baseURL/players with args username,password to recieve array of avaliable player names
GET /players
< 200
< Content-Type: application/json
[
    "playerName1",
    "playerName2"
]


Make call to baseURL/currentQueueRequest with args username,password,playerTitle to recieve statusUpdate message. This call returns nothing but a statusUpdate message from the box will follow on usual topic
PUT /currentQueueRequest
> Content-Type: application/json
{
    nil
}
< 200


--
Queue Managment 

Maintain and inform about current queue of tracks to all interested parties (MusicBox & Clients). 
Notice capital letters to track properties (due to shortcut in go; might change latter)
--


Response to currentQueueRequest
GET statusUpdate
< 200
{   "command":"statusUpdate"
    "data":{ 
        "deviceName": "My Device Name"
        "isPlaying": 1
        "queue":[
            {
                "Url": "http://www.example.com/123", 
                "TrackName":"Get Lucky", 
                "ArtistName": "Daft Punk",
                "AlbumName": "Random Access Memories",
                "Service": "Spotify", 
            }
        ]
    }
}