HOST: baseURL/username/deviceName/currentQueue

--- Project Music Box v1 ---

---
Documentation of WAMP protocol between MusicBox & clients
---

--
Track Handling

Used to modify the queue
--

Message sent to add array of tracks to all listeners
GET /addTrack
< 200
< Content-Type: application/json
{  "command":"addTrack"
   "data": [
        {
            "url": "http://www.example.com/123", 
            "trackName":"Get Lucky", 
            "artistName": "Daft Punk", 
            "service": "Spotify", 
        }
    ] 
}

--
Control Commands

Isssued to control music box playback
--

GET /playTrack
< 200
< Content-Type: application/json
{  
    "command":"playTrack"
}

GET /pauseTrack
< 200
< Content-Type: application/json
{  
    "command":"pauseTrack"
}


--
Queue Managment 

Maintain and inform about current queue of tracks to all interested parties (MusicBox & Clients) 
--


GET statusUpdate
< 200
{   "command":"statusUpdate"
    "data":{ 
        "isPlaying": 1
        "queue":[
            {
                "url": "http://www.example.com/123", 
                "trackName":"Get Lucky", 
                "artistName": "Daft Punk", 
                "service": "Spotify", 
            }
        ]
    }
}